# traefik.yml

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"

providers:
  docker:
    exposedByDefault: false

http:
  routers:
    app:
      rule: "Host(`kartaca.localhost`) && PathPrefix(`/app`)"
      service: "app-service"
      
    grafana:
      rule: "Host(`kartaca.localhost`) && Path(`/grafana`)"
      service: "grafana-service"

  services:
    app-service:
      loadBalancer:
        servers:
          - url: "localhost:4444/staj"

    grafana-service:
      loadBalancer:
        servers:
          - url: "localhost:3000"
